/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Hypermedia links for related resources
 */
export type _CustomerListItemLinks = {
  /** URL to fetch transportation orders for this customer */
  orders?: string;
};
