/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CargoType } from './cargoType';
import type { PalletType } from './palletType';

/**
 * Payload for adding a cargo unit to a load plan.
 */
export interface AddCargoInput {
  palletType: PalletType;
  cargoType: CargoType;
  /**
   * Weight of the cargo in kilograms
   * @exclusiveMinimum 0
   */
  weightKg: number;
  /**
   * Height of the cargo (without pallet) in millimetres
   * @exclusiveMinimum 0
   */
  cargoHeightMm: number;
}
