/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for assigning a driver to a transportation order.
 */
export interface AssignDriverInput {
  /** ID of the driver to assign to the order. */
  driver_id: number;
}
