/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current status of the load plan
 */
export type CargoLoadPlanStatus = typeof CargoLoadPlanStatus[keyof typeof CargoLoadPlanStatus];


export const CargoLoadPlanStatus = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
} as const;
