/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of cargo being transported
 */
export type CargoType = typeof CargoType[keyof typeof CargoType];


export const CargoType = {
  FOOD: 'FOOD',
  CHEMICAL: 'CHEMICAL',
  ELECTRONICS: 'ELECTRONICS',
  ADR: 'ADR',
  GENERAL: 'GENERAL',
} as const;
