/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CargoLoadPlanStatus } from './cargoLoadPlanStatus';
import type { PalletUnitReadModel } from './palletUnitReadModel';
import type { TrailerReadModel } from './trailerReadModel';
import type { WeightUnit } from './weightUnit';

/**
 * Full state of a cargo load plan.
 */
export interface CargoLoadPlanReadModel {
  /** Unique identifier of the load plan */
  id: string;
  status: CargoLoadPlanStatus;
  /**
   * Optimistic concurrency version of the load plan
   * @minimum 0
   */
  version: number;
  weightUnit: WeightUnit;
  trailer: TrailerReadModel;
  /**
   * Currently used loading metres
   * @minimum 0
   */
  currentLdm: number;
  /**
   * Total weight of all assigned cargo units, expressed in the unit given by weightUnit
   * @minimum 0
   */
  plannedWeight: number;
  /** Cargo units assigned to this plan */
  units: PalletUnitReadModel[];
}
