/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Special handling requirements for a cargo unit.
 */
export interface CargoRequirementsInput {
  /** Cargo requires a refrigerated trailer */
  isTemperatureControlled: boolean;
  /** Cargo must be loaded from the side */
  requiresSideLoading: boolean;
  /** Cargo is bulk (requires bulk-ready trailer) */
  isBulk: boolean;
  /** Cargo requires high-security locking */
  highSecurityRequired: boolean;
}
