/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { TrailerType } from './trailerType';

/**
 * Payload for changing the trailer type on a load plan.
 */
export interface ChangeTrailerInput {
  trailerType: TrailerType;
}
