/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Identifier of the newly created load plan.
 */
export interface CreateLoadPlanResponse {
  /** UUID of the created load plan */
  id: string;
}
