/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { _CustomerListItemLinks } from './_customerListItemLinks';

/**
 * A single customer record as returned in list responses.
 */
export interface CustomerListItem {
  /** Unique customer identifier */
  id: number;
  /**
   * Customer first name
   * @maxLength 50
   * @nullable
   */
  first_name?: string | null;
  /**
   * Customer last name
   * @maxLength 50
   * @nullable
   */
  last_name?: string | null;
  /**
   * Customer email address
   * @maxLength 100
   * @nullable
   */
  email?: string | null;
  /**
   * Customer phone number
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  /**
   * Customer classification (e.g. BUSINESS, INDIVIDUAL)
   * @maxLength 20
   * @nullable
   */
  customer_type?: string | null;
  /** Hypermedia links for related resources */
  _links?: _CustomerListItemLinks;
}
