/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerOrderSummary } from './customerOrderSummary';

/**
 * Full customer record including all fields and associated orders summary.
 */
export interface CustomerDetail {
  /** Unique customer identifier */
  id: number;
  /**
   * Customer first name
   * @maxLength 50
   * @nullable
   */
  first_name?: string | null;
  /**
   * Customer last name
   * @maxLength 50
   * @nullable
   */
  last_name?: string | null;
  /**
   * Customer email address
   * @maxLength 100
   * @nullable
   */
  email?: string | null;
  /**
   * Customer phone number
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  /**
   * Customer classification (e.g. BUSINESS, INDIVIDUAL)
   * @maxLength 20
   * @nullable
   */
  customer_type?: string | null;
  /**
   * Customer address
   * @maxLength 255
   * @nullable
   */
  address?: string | null;
  /** Optimistic locking version counter – must be passed in PATCH requests */
  version: number;
  /** Summary of transportation orders associated with this customer */
  orders: CustomerOrderSummary[];
}
