/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerListItem } from './customerListItem';
import type { Pagination } from './pagination';

/**
 * Paginated list of customers.
 */
export interface CustomerListResponse {
  data: CustomerListItem[];
  pagination: Pagination;
}
