/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Brief summary of a transportation order linked to a customer.
 */
export interface CustomerOrderSummary {
  /** Order identifier */
  id: number;
  /** Human-readable order number */
  order_number: string;
  /** Order total amount */
  amount: number;
  /** Current order status */
  status: string;
}
