/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Updated customer data returned after a successful PATCH.
 */
export interface CustomerPatchResponse {
  /** Unique customer identifier */
  id: number;
  /**
   * Updated first name
   * @nullable
   */
  first_name?: string | null;
  /**
   * Updated last name
   * @nullable
   */
  last_name?: string | null;
  /** Incremented version number after the update */
  version: number;
}
