/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for partially updating a customer's name. `version` (optimistic lock) is required. At least one of `first_name` or `last_name` must be provided.

 */
export interface CustomerPatchInput {
  /**
   * Current version of the customer record (used for optimistic locking)
   * @minimum 1
   */
  version: number;
  /**
   * New first name (optional – provide to update)
   * @maxLength 50
   */
  first_name?: string;
  /**
   * New last name (optional – provide to update)
   * @maxLength 50
   */
  last_name?: string;
}
