/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { DriverLicense } from './driverLicense';

/**
 * Full driver record including associated licenses (returned by GET /drivers/{id}).
 */
export interface DriverDetail {
  /** Unique driver identifier */
  id: number;
  /**
   * Driver first name
   * @maxLength 50
   * @nullable
   */
  first_name?: string | null;
  /**
   * Driver last name
   * @maxLength 50
   * @nullable
   */
  last_name?: string | null;
  /**
   * Driver email address
   * @maxLength 100
   * @nullable
   */
  email?: string | null;
  /**
   * Driver phone number
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  /**
   * Contract type (e.g. CONTRACTOR, FULL_TIME)
   * @maxLength 20
   * @nullable
   */
  contract_type?: string | null;
  /**
   * Driver status
   * @maxLength 20
   * @nullable
   */
  status?: string | null;
  /** Associated driver licenses with type details */
  licenses: DriverLicense[];
}
