/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Driver license record with license type details (returned in driver detail).
 */
export interface DriverLicense {
  /** License record identifier */
  id?: number;
  /**
   * License document number
   * @nullable
   */
  document_number?: string | null;
  /**
   * License issue date (YYYY-MM-DD)
   * @nullable
   */
  issue_date?: string | null;
  /**
   * License expiry date (YYYY-MM-DD)
   * @nullable
   */
  expiry_date?: string | null;
  /**
   * License status (e.g. active)
   * @nullable
   */
  status?: string | null;
  /**
   * License type code
   * @nullable
   */
  code?: string | null;
  /**
   * License type name
   * @nullable
   */
  name?: string | null;
  /**
   * License type description
   * @nullable
   */
  description?: string | null;
}
