/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Standard error envelope returned on 4xx / 5xx responses.
 */
export interface ErrorResponse {
  /** Human-readable error message. */
  error: string;
}
