/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { WeightUnit } from './weightUnit';
import type { WeightUnitParamParameter } from './weightUnitParamParameter';

export type GetLoadPlanParams = {
/**
 * Unit of weight measurement
 */
weightUnit?: WeightUnitParamParameter;
};
