/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { LimitParamParameter } from './limitParamParameter';
import type { PageParamParameter } from './pageParamParameter';

export type GetNotificationsByUserIdParams = {
/**
 * User ID to fetch notifications for. Required.
 * @pattern ^[1-9]\d*$
 */
userId: string;
/**
 * Page number (1-based)
 */
page?: PageParamParameter;
/**
 * Number of items per page (max 100)
 */
limit?: LimitParamParameter;
};
