/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

export type GetTransportationOrdersParams = {
/**
 * Filter orders by customer ID. When omitted, returns all orders.
 */
customer_id?: string;
};
