/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Health check response body.
 */
export interface HealthResponse {
  /** Health status (always "ok" when the service is running) */
  status: string;
  /** Service name (from SERVICE_NAME env or default tms-api) */
  service: string;
}
