/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { Notification } from './notification';
import type { Pagination } from './pagination';

/**
 * Paginated list of notifications.
 */
export interface NotificationListResponse {
  data: Notification[];
  pagination: Pagination;
}
