/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A single notification as returned by the API.
 */
export interface Notification {
  /** Unique notification identifier */
  id: number;
  /** ID of the user who receives the notification */
  user_id: number;
  /**
   * Notification type (e.g. warning, success)
   * @maxLength 20
   */
  type: string;
  /** Notification message content */
  message: string;
  /** When the notification was created (ISO 8601) */
  created_at: string;
  /** Whether the notification has been read */
  is_read: boolean;
}
