/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination metadata attached to list responses.
 */
export interface Pagination {
  /** Current page number (1-based) */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of records across all pages */
  total: number;
  /** Total number of pages */
  totalPages: number;
}
