/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported pallet types
 */
export type PalletType = typeof PalletType[keyof typeof PalletType];


export const PalletType = {
  epal1: 'epal1',
  industrial: 'industrial',
  half: 'half',
  cp1: 'cp1',
  cp3: 'cp3',
  h1: 'h1',
} as const;
