/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Capabilities of the assigned trailer.
 */
export interface TrailerCapabilities {
  /** Trailer has temperature/climate control */
  hasClimateControl: boolean;
  /** Trailer supports side loading */
  supportsSideLoading: boolean;
  /** Trailer has high-security locking */
  hasHighSecurityLock: boolean;
  /** Trailer supports bulk cargo */
  isBulkReady: boolean;
}
