/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import type { TrailerCapabilities } from './trailerCapabilities';
import type { TrailerType } from './trailerType';

/**
 * Details of the trailer assigned to the load plan.
 */
export interface TrailerReadModel {
  type: TrailerType;
  canCarryPallets: boolean;
  /** Maximum weight capacity in kilograms */
  maxWeightCapacityKg: number;
  /** Internal trailer width in millimetres */
  widthMm: number;
  /** Internal trailer height in millimetres */
  heightMm: number;
  /** Maximum loading metres (LDM) */
  maxLdm: number;
  capabilities: TrailerCapabilities;
}
