/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A single transportation order as returned by the API.
 */
export interface TransportationOrder {
  /** Unique order identifier */
  id: number;
  /**
   * Human-readable order number (e.g.
   * @maxLength 20
   */
  order_number: string;
  /** ID of the customer who placed the order */
  customer_id: number;
  /**
   * ID of the driver assigned to this order. Null when no driver has been assigned yet.
   * @nullable
   */
  driver_id?: number | null;
  /**
   * Order status (e.g. DELIVERED, PENDING)
   * @maxLength 20
   */
  status: string;
  /** Order total amount. Returned as a decimal string (e.g. "43.19") because Postgres numeric is serialised as a string by the pg driver.
 */
  amount: string;
  /** When the order was placed (ISO 8601) */
  order_date: string;
  /**
   * Expected delivery date (ISO 8601; Postgres date may be serialised with time component)
   * @nullable
   */
  expected_delivery?: string | null;
  /**
   * Delivery street address
   * @maxLength 255
   * @nullable
   */
  shipping_address?: string | null;
  /**
   * Delivery city
   * @maxLength 100
   * @nullable
   */
  shipping_city?: string | null;
  /**
   * Delivery state or region
   * @maxLength 50
   * @nullable
   */
  shipping_state?: string | null;
  /**
   * Delivery postal code
   * @maxLength 20
   * @nullable
   */
  shipping_zip_code?: string | null;
  /**
   * Shipping method name
   * @maxLength 50
   * @nullable
   */
  shipping_method?: string | null;
  /**
   * Carrier tracking number
   * @maxLength 50
   * @nullable
   */
  tracking_number?: string | null;
}
