/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * A single vehicle record as returned by the API.
 */
export interface Vehicle {
  /** Unique vehicle identifier */
  id: number;
  /**
   * Vehicle manufacturer / brand
   * @maxLength 50
   * @nullable
   */
  make?: string | null;
  /**
   * Vehicle model name
   * @maxLength 50
   */
  model: string;
  /**
   * Manufacturing year
   * @nullable
   */
  year?: number | null;
  /**
   * Fuel tank capacity in litres. Returned as a decimal string (e.g. "51.1") because Postgres numeric/decimal is serialised as a string by the pg driver.

   * @nullable
   */
  fuel_tank_capacity?: string | null;
}
