/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for creating a new vehicle. Only `model` is required.
 */
export interface VehicleCreateInput {
  /**
   * Vehicle manufacturer / brand
   * @maxLength 50
   * @nullable
   */
  make?: string | null;
  /**
   * Vehicle model name
   * @maxLength 50
   */
  model: string;
  /**
   * Manufacturing year
   * @nullable
   */
  year?: number | null;
  /**
   * Fuel tank capacity in litres (positive number)
   * @exclusiveMinimum 0
   * @nullable
   */
  fuel_tank_capacity?: number | null;
}
