/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Unit of weight measurement
 */
export type WeightUnit = typeof WeightUnit[keyof typeof WeightUnit];


export const WeightUnit = {
  KG: 'KG',
  TONNE: 'TONNE',
  LB: 'LB',
} as const;
