PL = [
    "A w sercu ciągle maj.",
    "Bądźmy poważni. Chyba nie myślałeś, że ci odpuścimy?",
    "Człowiek całe życie się uczy i głupi umiera.",
    "Jeszcze Polska nie zginęła, kiedy my żyjemy.",
    "Kobieta mnie bije.",
    "Koniec i bomba, a kto czytał ten trąba.",
    "Mnie się podoba ten typ, co ma w oczach coś.",
    "No i wreszcie się doczekali. Koniec polskiej komuny.",
    "Sąd sądem, a sprawiedliwość musi być po naszej stronie.",
    "Zaraz wracam.",
    "I co, łyso wam?",
    "Kobieta mnie bije.",
    "W marcu jak w garncu.",
    "Lata, całe lata, całe lata...",
    "Nie matura, lecz chęć szczera zrobi z ciebie oficera.",
    "A może by tak rzucić to wszystko i wyjechać w Bieszczady?",
    "Zaraz wracam.",
    "Fortuna kołem się toczy.",
    "Miś jest na skalę naszych możliwości.",
    "Chłop żywemu nie przepuści."
]

EN = [
    "To be, or not to be, that is the question.",
    "May the Force be with you.",
    "Frankly, my dear, I don’t give a damn.",
    "E.T. phone home.",
    "We hold these truths to be self-evident.",
    "I have a dream.",
    "Elementary, my dear Watson.",
    "Here’s looking at you, kid.",
    "The only thing we have to fear is fear itself.",
    "Houston, we have a problem.",
    "May the Force be with you.",
    "Here's looking at you, kid.",
    "Houston, we have a problem.",
    "Elementary, my dear Watson.",
    "E.T. phone home.",
    "A rose by any other name would smell as sweet.",
    "I'm going to make him an offer he can't refuse.",
    "I have a dream.",
    "We're not in Kansas anymore.",
    "This is the way.",
]