/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetNotificationsByUserIdParams,
  NotificationListResponse
} from '../model';




  export const getNotifications = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a paginated list of notifications for the given user. Results are ordered by created_at descending.
 * @summary List notifications by user
 */
const getNotificationsByUserId = (
    params: GetNotificationsByUserIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NotificationListResponse>> => {
    return axiosInstance.get(
      `/notifications`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getNotificationsByUserId}};
export type GetNotificationsByUserIdResult = AxiosResponse<NotificationListResponse>
