package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"tms-data-generator/generator/cargo_plans"
	"tms-data-generator/generator/config"
)

const cargoPlansOutputBanner = `
-- SQL generated by tms-data-generator (cargo_plans schema)
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit the create-tms-cargo-plans.sql file instead
--
-- Schema: cargo_plans
-- Contains: cargo_load_plans, cargo_load_plan_units
`

// GenerateCargoPlans generates the cargo plans SQL file.
// It creates the cargo_plans schema DDL followed by INSERT statements.
func GenerateCargoPlans(outputFile string) error {
	outputDir := filepath.Dir(outputFile)
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("error creating output directory '%s': %w", outputDir, err)
	}

	schema, err := os.ReadFile("schema/create-tms-cargo-plans.sql")
	if err != nil {
		return fmt.Errorf("error reading cargo plans schema file: %w", err)
	}

	start := time.Now()
	fmt.Println("Generating cargo load plans...", time.Now())

	plans := cargo_plans.GenerateCargoLoadPlans(config.CARGO_LOAD_PLANS)

	plansSQL := cargo_plans.GeneratePlanInsertStatements(plans)
	unitsSQL := cargo_plans.GenerateUnitInsertStatements(plans)

	fmt.Printf("Generated %d plans, done in %s\n", len(plans), time.Since(start))

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("-- Generated on: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(cargoPlansOutputBanner)
	sb.Write(schema)
	sb.WriteString("\n")
	sb.WriteString(plansSQL)
	sb.WriteString(unitsSQL)

	if err := os.WriteFile(outputFile, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("error writing file to '%s': %w", outputFile, err)
	}

	fmt.Println("Cargo plans SQL file generated:", outputFile)
	return nil
}
