/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetVehiclesParams,
  Vehicle,
  VehicleCreateInput,
  VehicleListResponse,
  VehicleUpdateInput
} from '../model';




  export const getVehicles = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a paginated list of all vehicles.
 * @summary List vehicles
 */
const getVehicles = (
    params?: GetVehiclesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VehicleListResponse>> => {
    return axiosInstance.get(
      `/vehicles`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Creates a new vehicle record.
 * @summary Create a vehicle
 */
const createVehicle = (
    vehicleCreateInput: VehicleCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Vehicle>> => {
    return axiosInstance.post(
      `/vehicles`,
      vehicleCreateInput,options
    );
  }
/**
 * Returns a single vehicle by its numeric ID.
 * @summary Get vehicle by ID
 */
const getVehicleById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Vehicle>> => {
    return axiosInstance.get(
      `/vehicles/${id}`,options
    );
  }
/**
 * Replaces vehicle data. All fields are optional – only provided fields are updated.
 * @summary Update a vehicle
 */
const updateVehicle = (
    id: number,
    vehicleUpdateInput: VehicleUpdateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Vehicle>> => {
    return axiosInstance.put(
      `/vehicles/${id}`,
      vehicleUpdateInput,options
    );
  }
/**
 * Permanently deletes a vehicle by its ID.
 * @summary Delete a vehicle
 */
const deleteVehicle = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/vehicles/${id}`,options
    );
  }
return {getVehicles,createVehicle,getVehicleById,updateVehicle,deleteVehicle}};
export type GetVehiclesResult = AxiosResponse<VehicleListResponse>
export type CreateVehicleResult = AxiosResponse<Vehicle>
export type GetVehicleByIdResult = AxiosResponse<Vehicle>
export type UpdateVehicleResult = AxiosResponse<Vehicle>
export type DeleteVehicleResult = AxiosResponse<void>
