/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DriverCreateInput,
  DriverDetail,
  DriverListItem
} from '../model';




  export const getDrivers = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a list of all drivers (up to 100). No pagination.
 * @summary List drivers
 */
const getDrivers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DriverListItem[]>> => {
    return axiosInstance.get(
      `/drivers`,options
    );
  }
/**
 * Creates a new driver record. All fields are optional.
 * @summary Create a driver
 */
const createDriver = (
    driverCreateInput: DriverCreateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DriverListItem>> => {
    return axiosInstance.post(
      `/drivers`,
      driverCreateInput,options
    );
  }
/**
 * Returns a single driver with their associated driver licenses.
 * @summary Get driver by ID
 */
const getDriverById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DriverDetail>> => {
    return axiosInstance.get(
      `/drivers/${id}`,options
    );
  }
return {getDrivers,createDriver,getDriverById}};
export type GetDriversResult = AxiosResponse<DriverListItem[]>
export type CreateDriverResult = AxiosResponse<DriverListItem>
export type GetDriverByIdResult = AxiosResponse<DriverDetail>
