/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CustomerDetail,
  CustomerListResponse,
  CustomerPatchInput,
  CustomerPatchResponse,
  GetCustomersParams
} from '../model';




  export const getCustomers = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a paginated list of customers. Supports optional full-text search by first or last name.
 * @summary List customers
 */
const getCustomers = (
    params?: GetCustomersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CustomerListResponse>> => {
    return axiosInstance.get(
      `/customers`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Returns a single customer with their full details and a summary of associated transportation orders.
 * @summary Get customer by ID
 */
const getCustomerById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CustomerDetail>> => {
    return axiosInstance.get(
      `/customers/${id}`,options
    );
  }
/**
 * Partially updates a customer's first and/or last name. Uses optimistic locking – the request must include the current `version` value. If the resource was modified by another request since it was last read, a 409 conflict is returned.

 * @summary Update customer name
 */
const patchCustomer = (
    id: number,
    customerPatchInput: CustomerPatchInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CustomerPatchResponse>> => {
    return axiosInstance.patch(
      `/customers/${id}`,
      customerPatchInput,options
    );
  }
/**
 * Permanently deletes a customer by their ID.
 * @summary Delete a customer
 */
const deleteCustomer = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/customers/${id}`,options
    );
  }
return {getCustomers,getCustomerById,patchCustomer,deleteCustomer}};
export type GetCustomersResult = AxiosResponse<CustomerListResponse>
export type GetCustomerByIdResult = AxiosResponse<CustomerDetail>
export type PatchCustomerResult = AxiosResponse<CustomerPatchResponse>
export type DeleteCustomerResult = AxiosResponse<void>
