/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AssignDriverInput,
  GetTransportationOrdersParams,
  TransportationOrder
} from '../model';




  export const getTransportationOrders = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a list of transportation orders, optionally filtered by customer ID. Results are ordered by order_date descending, limited to 100 items.
 * @summary List transportation orders
 */
const getTransportationOrders = (
    params?: GetTransportationOrdersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TransportationOrder[]>> => {
    return axiosInstance.get(
      `/transportation-orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Assigns an existing driver to the specified transportation order. Replaces any previously assigned driver. The operation is idempotent.
 * @summary Assign a driver to a transportation order
 */
const assignDriverToOrder = (
    id: number,
    assignDriverInput: AssignDriverInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/transportation-orders/${id}/driver`,
      assignDriverInput,options
    );
  }
return {getTransportationOrders,assignDriverToOrder}};
export type GetTransportationOrdersResult = AxiosResponse<TransportationOrder[]>
export type AssignDriverToOrderResult = AxiosResponse<void>
