/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HealthResponse
} from '../model';




  export const getStatus = (axiosInstance: AxiosInstance = axios) => {
/**
 * Returns a plain-text message with server start time and uptime.
 * @summary Server status
 */
const getServerStatus = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.get(
      `/`,{
        responseType: 'text',
    ...options,}
    );
  }
/**
 * Returns a JSON object indicating the service is healthy. Used by load balancers and monitoring.
 * @summary Health check
 */
const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HealthResponse>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }
return {getServerStatus,getHealth}};
export type GetServerStatusResult = AxiosResponse<string>
export type GetHealthResult = AxiosResponse<HealthResponse>
