/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TMS API
 * Transportation Management System API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddCargoInput,
  CargoLoadPlanReadModel,
  ChangeTrailerInput,
  CreateLoadPlanInput,
  CreateLoadPlanResponse,
  GetLoadPlanParams
} from '../model';




  export const getCargoPlans = (axiosInstance: AxiosInstance = axios) => {
/**
 * Creates a new cargo load plan for a given trailer type.
 * @summary Create a load plan
 */
const createLoadPlan = (
    createLoadPlanInput: CreateLoadPlanInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateLoadPlanResponse>> => {
    return axiosInstance.post(
      `/cargo-plans`,
      createLoadPlanInput,options
    );
  }
/**
 * Returns the full state of a load plan including assigned cargo units.
 * @summary Get load plan details
 */
const getLoadPlan = (
    id: string,
    params?: GetLoadPlanParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CargoLoadPlanReadModel>> => {
    return axiosInstance.get(
      `/cargo-plans/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Adds a pallet unit with cargo to an existing draft load plan.
 * @summary Add cargo to a load plan
 */
const addCargoToLoadPlan = (
    id: string,
    addCargoInput: AddCargoInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/cargo-plans/${id}/cargo`,
      addCargoInput,options
    );
  }
/**
 * Removes a specific pallet unit from a draft load plan by its unit ID.
 * @summary Remove cargo from a load plan
 */
const removeCargoFromLoadPlan = (
    id: string,
    unitId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/cargo-plans/${id}/cargo/${unitId}`,options
    );
  }
/**
 * Replaces the trailer on a draft load plan. All currently assigned cargo units are re-validated against the new trailer's capabilities and capacity.
 * @summary Change trailer type
 */
const changeTrailerType = (
    id: string,
    changeTrailerInput: ChangeTrailerInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/cargo-plans/${id}/trailer`,
      changeTrailerInput,options
    );
  }
/**
 * Marks the load plan as FINALIZED. A finalized plan cannot be modified. The plan must have at least one cargo unit and must not exceed trailer capacity.
 * @summary Finalize a load plan
 */
const finalizeLoadPlan = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/cargo-plans/${id}/finalize`,undefined,options
    );
  }
return {createLoadPlan,getLoadPlan,addCargoToLoadPlan,removeCargoFromLoadPlan,changeTrailerType,finalizeLoadPlan}};
export type CreateLoadPlanResult = AxiosResponse<CreateLoadPlanResponse>
export type GetLoadPlanResult = AxiosResponse<CargoLoadPlanReadModel>
export type AddCargoToLoadPlanResult = AxiosResponse<void>
export type RemoveCargoFromLoadPlanResult = AxiosResponse<void>
export type ChangeTrailerTypeResult = AxiosResponse<void>
export type FinalizeLoadPlanResult = AxiosResponse<void>
